### ISSUE TITLE
hw93 feedback

### ISSUE THREAD

**Issue by DavidHolmes0** [joyceliaoo/eggs#1]
You have posted essentially no work on the assignments. C'mon people; your team is better than this.

**Comment by joyceliaoo** [comment]
I agree that we haven’t completed the assignments to their entirety, but we have made attempts for the first five sections required. I don’t think it’s fair to say we have done “no work” just because we have yet to fix a formatting issue and have two slightly different answers to the recursive abstraction section and the algorithm. We didn’t want to completely get rid a person’s work before we are confident in a finalized version. I understand that our work does not deserve a 3/3, but I don’t see how the work we have put in is counted as “none”.

**Comment by DavidHolmes0** [comment]
My bad. Please see [Piazza@457](https://piazza.com/class/j7oyiev6r7x576?cid=457). 

On a personal note, I'm pleased to see that the apparent lack of work is my misunderstanding git, not the incompetence of Team eggs. That accords better with my impression of you people.

**Comment by DavidHolmes0** [comment]
The initial comment in this issue was based on an old snapshot of your work, as discussed in [Piazza@457](https://piazza.com/class/j7oyiev6r7x576?cid=457). Please ignore discussion of problems you have already fixed.

This later version is solid work.

## recursive abstraction
You have 2 versions as of this writing, which you will edit down to one, if I understand Joyce's "We didn’t want to completely get rid a person’s work" above. Fine. Based on the note, the two forms are equivalent. The second is easier for this reader to understand, in case that helps you.
